[colors.normal]
black = "#000000"
red = "#7a264a"
green = "#a2446c"
yellow = "#f7e59b"
blue = "#f3bbad"
magenta = "#f79ed0"
cyan = "#f474bc"
white = "#ffffff"

[colors.bright]
black = "#3a2343"
red = "#7a264a"
green = "#a2446c"
yellow = "#f7e59b"
blue = "#f3bbad"
magenta = "#f79ed0"
cyan = "#f474bc"
white = "#ffffff"

[colors.dim]
black = "#3a2343"
red = "#7a264a"
green = "#a2446c"
yellow = "#f7e59b"
blue = "#f3bbad"
magenta = "#f79ed0"
cyan = "#f474bc"
white = "#ffffff"

[colors.primary]
background = "#000000"
bright_foreground = "#f689c6"
dim_foreground = "#982f5c"
foreground = "#ffffff"

[colors.cursor]
cursor = "#f79ed0"
text = "#ffffff"

[colors.vi_mode_cursor]
cursor = "#a2446c"
text = "#ffffff"

[colors.selection]
background = "#7a264a"
text = "#ffffff"
