audio_device = "default"
min_freq = 20
max_freq = 4500
default_gain = 0.5
transition_time = 2
hues = [
    60,
    44,
    28,
    12,
    356,
    340,
    324,
    308,
    292,
    276,
    260,
    244,
]

[nl_config]
primary_axis = "y"
sort_primary = "desc"
sort_secondary = "desc"
active_panels = [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
]
token_file_path = "/home/antek/.config/audioleaf/nltoken"
ip = "192.168.0.101"
port = 6789
