default_nl_device_name = "Canvas 2E50"

[tui_config]
colorful_effect_names = true

[visualizer_config]
audio_backend = "default"
freq_range = [
    20,
    4500,
]
hues = [
    35,
    15,
    355,
    335,
    315,
    295,
    275,
    255,
    235,
    215,
    195,
    175,
]
default_gain = 1.0
transition_time = 2
time_window = 0.1875
primary_axis = "Y"
sort_primary = "Asc"
sort_secondary = "Asc"
