default_nl_device_name = "Canvas DD79"

[tui_config]
colorful_effect_names = true

[visualizer_config]
audio_backend = "default"
freq_range = [
    20,
    4500,
]
hues = [
    25,
    30,
    35,
    30,
    25,
    35,
    35,
    25,
    30,
    35,
    30,
    25,
]
default_gain = 1.0
transition_time = 2
time_window = 0.1875
primary_axis = "Y"
sort_primary = "Asc"
sort_secondary = "Asc"
