#!/usr/bin/env bash

[[ $(hostname) == "antek-zenbook" ]] || exit

percent=$(acpi -b | awk '{print $4}' | sed "s/..$//")
regex="^[0-9]+$"

symbols=(󱃍 󰁺 󰁻 󰁼 󰁽 󰁾 󰁿 󰂀 󰂁 󰂂 󰁹)
level=$(( percent / 10 ))
echo -n ${symbols[level]}
echo " $percent%"
echo
if [[ $percent -ge 50 ]]; then
    echo "#9CCFD8"
elif [[ $percent -ge 25 ]]; then
    echo "#F6C177"
else
    echo "#EB6F92"
fi
