#!/usr/bin/env bash
[[ $(hostname) == "antek-zenbook" ]] || exit

percent=$(acpi -b | awk '{print $4}' | sed "s/..$//")

symbols=(󱃍 󰁺 󰁻 󰁼 󰁽 󰁾 󰁿 󰂀 󰂁 󰂂 󰁹)
level=$(( percent / 10 ))
echo -n ${symbols[level]}
echo " $percent%"
echo
if [[ $percent -ge 50 ]]; then
    echo "#B21B3C"
elif [[ $percent -ge 25 ]]; then
    echo "#F14985"
else
    echo "#FCF16D"
fi
