#!/usr/bin/env zsh

percent=$(acpi -b | awk '{print $4}' | sed "$ s/.$//" | sed "$ s/.$//")
if ! [[ $percent =~ "^[0-9]+$" ]]; then
    exit
fi

if [[ $percent -eq 100 ]]; then
    echo -n "󰁹"
elif [[ $percent -ge 90 ]]; then
    echo -n "󰂂"
elif [[ $percent -ge 80 ]]; then
    echo -n "󰂁"
elif [[ $percent -ge 70 ]]; then
    echo -n "󰂀"
elif [[ $percent -ge 60 ]]; then
    echo -n "󰁿"
elif [[ $percent -ge 50 ]]; then
    echo -n "󰁾"
elif [[ $percent -ge 40 ]]; then
    echo -n "󰁽"
elif [[ $percent -ge 30 ]]; then
    echo -n "󰁼"
elif [[ $percent -ge 20 ]]; then
    echo -n "󰁻"
else
    echo -n "󰁺"
fi

echo " $percent%"
echo
if [[ $percent -ge 50 ]]; then
    echo "#9CCFD8"
elif [[ $percent -ge 25 ]]; then
    echo "#F6C177"
else
    echo "#EB6F92"
fi
