#!/usr/bin/env bash

total=$(free | awk 'NR==2 {print $2}')
used=$(free | awk 'NR==2 {print $3}')
percent=$(((100 * used) / total))
echo "$percent%"
echo
if [[ $percent -le 25 ]]; then
    echo "#9CCFD8"
elif [[ $percent -le 50 ]]; then
    echo "#F6C177"
else
    echo "#EB6F92"
fi
