#!/usr/bin/env bash
total=$(free | awk 'NR==2 {print $2}')
used=$(free | awk 'NR==2 {print $3}')
percent=$(((100 * used) / total))
echo "$percent%"
echo
if [[ $percent -ge 50 ]]; then
    echo "#FCF16D"
elif [[ $percent -ge 25 ]]; then
    echo "#F14985"
else
    echo "#B21B3C"
fi
