#!/usr/bin/env bash

total=$(free | awk 'NR==2 {print $2}')
used=$(free | awk 'NR==2 {print $3}')
percent=$(((100 * used) / total))
echo "$percent%"
echo
if [[ $percent -le 25 ]]; then
    echo "#DA6080"
elif [[ $percent -le 50 ]]; then
    echo "#B47F91"
else
    echo "#FBF785"
fi
