#!/usr/bin/env bash

mpc_out="$(mpc)"
song=$(echo "$mpc_out" | awk 'NR == 1')
state=$(echo "$mpc_out" | awk 'NR == 2' | grep -o "\[[a-z]*\]")
if [[ $state == "[playing]" ]]; then
    echo " $song"
elif [[ $state == "[paused]" ]]; then
    echo " $song"
else
    echo "mpd stopped"
fi
