#!/usr/bin/env zsh
# get the currenly playing song on MPD
IFS= # so that newlines don't get lost in the next line
mpc_out="$(mpc)"
song=$(echo $mpc_out | sed -n "1p")
state=$(echo $mpc_out | sed -n "2p" | grep -o "\[[a-z]*\]")
if [[ $state == "[playing]" ]]; then
    echo -n " "
elif [[ $state == "[paused]" ]]; then
    echo -n " "
else
    echo -n " "
fi
echo $song
