#!/usr/bin/env bash

volume_msg=$(wpctl get-volume @DEFAULT_SINK@)
if [[ $volume_msg =~ "MUTED" ]]; then
    echo 󰝟
    exit
fi
volume=$(echo "$volume_msg" | awk '{print $2 * 100 }')
sink=$(pactl get-default-sink)
if [[ $sink =~ "bluez" ]]; then
    icon=
else
    icon=󰕾
fi
echo "$icon $volume%"
