#!/usr/bin/env bash
if [[ -z "$INTERFACE" ]] ; then
    INTERFACE="${BLOCK_INSTANCE:-wlan0}"
fi

[[ ! -d /sys/class/net/"${INTERFACE}"/wireless || \
    "$(cat /sys/class/net/"$INTERFACE"/operstate)" = 'down' ]] && exit

echo " "
