use_nerdfont = true
audio_cache_size = 2048
library_tabs = ["playlists", "podcasts", "browse"]

[credentials]
username_cmd = "echo AnZa"
password_cmd = "pass spotify"

[keybindings]
"Esc" = "quit"
"q" = "queue"
"Space" = "toggleplay"
"a" = "add"

[theme]
cmdline = "#e0def4"
cmdline_bg = "#191724"
playing = "#f6c177"
playing_bg = "#191724"
highlight = "#31748f"
highlight_bg = "#21202e"
error = "#eb6f92"
error_bg = "#191724"
