background = rgb(000000)
base = rgb(000000)
text = rgb(fefefe)
highlight = rgb(ff00ff)
accent = rgb(ff0000)

rounding_large = 0
rounding_small = 0

font_family = Noto Sans
font_family_monospace = Lilex Nerd Font
