#!/usr/bin/env bash
# adds a cover image to a song
# -u to provide an image url, -i to provide an image path

url=""
image=""
song=""

while getopts "u:i:s:" flag; do
    case "$flag" in
    "u")
        url="$OPTARG"
        ;;
    "i")
        image="$OPTARG"
        ;;
    "s")
        song="$OPTARG"
        ;;
    esac
done

if [[ -z "$song" ]]; then
    exit 1
fi

if [[ -n "$url" ]]; then
    image="/tmp/cover.jpg"
    wget "$url" -O "$image"
fi

echo "image: ${image}"
ffmpeg -i "$song" -i "$image" -c copy -disposition:v attached_pic "_${song}"
