#!/usr/bin/env bash
# Move latex temporary compilation files into ./aux/.

if [[ ! -d aux ]]; then
    mkdir aux
fi

\mv -f *.aux *.dvi *.fdb_latexmk *.fls *.log *.out *.thm *.toc *.err *.inf *.pre *-[0-9].pdf aux
