#!/usr/bin/env bash
# Compile previous lecture notes

if [[ -z $1 ]]; then
    exit 0
fi

class=$1
working_dir="$HOME/Notes/sem$SEMESTER/$class/lecture"
metadata_file="$working_dir/../metadata.json"
main_file_basename="$class.tex"
main_file="$working_dir/$main_file_basename"
main_file_header="$HOME/.config/latexmk/mainfileheader.tex"
header_text=$(cat $main_file_header)
 
commands=$(jq -r 'keys[] as $k | "s/{{\($k)}}/\(.[$k])/"' $metadata_file)
for command in "$commands"; do
    header_text=$(echo "$header_text" | sed "$command")
done
echo "$header_text" > $main_file

parts=$working_dir/parts/*.tex
for part in $parts; do
    echo "Adding $(basename $part)..."
    start=$(awk '$0 ~ "^%%%START" {print NR}' $part | tr -d '\n')
    end=$(awk '$0 ~ "^%%%END" {print NR}' $part | tr -d '\n')
    if [[ -z $start || -z $end ]]; then
        echo "Start and/or end markers not found in $(basename $part)"
        rm -f $main_file
        exit 1
    fi
    content=$(awk -v start=$start -v end=$end 'NR > start && NR < end' $part)
    echo "$content" >> $main_file
    echo "\pagebreak" >> $main_file
done

# remove the last pagebreak
sed -i '$ d' $main_file
echo "\end{document}" >> $main_file

echo "Compiling..."
latexmk -cd $main_file -pdflatex > /dev/null 2>&1 && rm -f $main_file
