#!/usr/bin/env bash
# Credit: ThePrimeagen's tmux-sessionizer
# Renamed to ff for convenience

chosen=$(find ~/Code/projects -mindepth 1 -maxdepth 1 -type d -not -path "*/.*" | fzf)

[[ -z $chosen ]] && exit 1

chosen_name=$(basename "$chosen" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $chosen_name -c $chosen
    exit 0
fi

if ! tmux has-session -t=$chosen_name 2> /dev/null; then
    tmux new-session -ds $chosen_name -c $chosen
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $chosen_name
else
    tmux switch-client -t $chosen_name
fi
