#!/usr/bin/env bash

chosen=$(fd --type d --hidden --exclude=".git" --search-path "$HOME/Code" 2>/dev/null | fzf)
[[ -z $chosen ]] && exit 1
chosen=${chosen::-1}

chosen_name=$(basename "$chosen" | tr "[:space:]" _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $chosen_name -c $chosen
    exit 0
fi

if ! tmux has-session -t=$chosen_name 2> /dev/null; then
    tmux new-session -ds $chosen_name -c $chosen
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $chosen_name
else
    tmux switch-client -t $chosen_name
fi
