#!/usr/bin/env bash
# Search through files and open them in corresponding programs

chosen=$({
	find ~/Notes/lectures/ -mindepth 1 -type f -name "*.pdf"
	find ~/Notes/books/ -mindepth 1 -type f -name "*.pdf"
	find ~/Notes/notes/ -mindepth 1 -type f -name "*.pdf"
    find ~/Notes/projects/ -mindepth 1 -type f \( -name "*.pdf" -o -name "*.jpg" -o -name "*.png" \)
    find ~/Pictures -mindepth 1 -type f \( -name "*.jpg" -o -name "*.png" \)
} | rofi -dmenu)

[[ -z $chosen ]] && exit 1

ext=${chosen##*.}
if [[ "$ext" == "pdf" ]]; then
    exec zathura $chosen
elif [[ "$ext" == "jpg" || "$ext" == "png" ]]; then
    exec imv $chosen
fi
