#!/usr/bin/env bash
# Take a screenshot and save it both to the clipboard and to disk

maim -o --hidecursor --select | tee ~/Pictures/screenshots/$(date +%Y-%m-%d_%H-%M-%S).png | xclip -selection clipboard -t image/png && notify-send "Screenshot saved"
