#!/usr/bin/env bash

options=("Shutdown" "Reboot")
commands=("systemctl poweroff -i" "systemctl reboot")
chosen=$(printf '%s\n' "${options[@]}" | rofi -dmenu -format i -i -theme-str 'mainbox {children: [listview];}')
if [[ -n $chosen && $chosen -ge 0 ]]; then
	exec ${commands[chosen]}
fi
