#! /usr/bin/env bash
hyprctl switchxkblayout all next
layout=$(hyprctl devices -j | jq -r '.keyboards[] | select(.main == true) | .active_keymap')
notify-send -t 1000 "Keyboard" "Switched to ${layout}"
