#!/bin/sh

alias mv="mv -vi"
alias cp="cp -vi"
alias rm="rm -vi"
alias mkdir="mkdir -v"

alias ls="eza --icons --group-directories-first"
alias ll="eza --all --icons --group-directories-first -l --git"

# others
alias tmux="tmux -2"
alias vim="nvim"
alias py="python"
alias ncmpcpp="ncmpcpp -q"
