#!/bin/sh

# better safe than sorry
alias mv="mv -vi"
alias cp="cp -vi"
alias rm="rm -vI"
alias mkdir="mkdir -pv"

# bat - cat replacement
alias cat="bat --style=plain --paging=never"

# eza - ls replacement 
alias ls="eza --icons --group-directories-first"
alias ll="eza --all --icons --group-directories-first -l --git"
alias tree="ls --tree"

# rip - safer rm
alias rip="rip --graveyard ~/.local/share/trash"

alias vim="nvim"
alias ff="cd ~/Documents && cd \$(find ~/Documents -type d \( -name debug -o -name .git \) -prune -o -name '*' -type d -print | fzf)"
