#!/bin/sh

# better safe than sorry
alias mv="mv -vi"
alias cp="cp -vi"
alias rm="rm -vi"
alias mkdir="mkdir -pv"

# bat - cat replacement
alias cat="bat --style=plain --paging=never"

# eza - ls replacement 
alias ls="eza --icons --group-directories-first"
alias ll="eza --all --icons --group-directories-first -l --git"
alias tree="ls --tree"

# rip - safer rm
alias rip="rip --graveyard ~/.local/share/trash"

# cp compilation
alias comp='make CXXFLAGS="-std=c++17 -Wall -Wextra -Wno-unused-parameter -Wshadow -Wfatal-errors -fsanitize=address,undefined -D_GLIBCXX_DEBUG"'

# others
alias tmux="tmux -2"
alias vim="nvim"
alias py="python"
