sub asy {return system("asy -o asy/ '$_[0]'");}
add_cus_dep("asy","eps",0,"asy");
add_cus_dep("asy","pdf",0,"asy");
add_cus_dep("asy","tex",0,"asy");

push @generated_exts, "pre";
push @generated_exts, "synctex.gz";
$success_cmd = "\\rm -f *.aux *.fdb_latexmk *.fls *.log *.out *.thm *.toc *.err *.inf";
