# sub asy {return system("asy -o '$_[0]' '$_[0]'");}
# sub asy {return system("asy '$_[0]'");}
# add_cus_dep("asy", "eps", 0, "asy");
# add_cus_dep("asy", "pdf", 0, "asy");
# add_cus_dep("asy", "tex", 0, "asy");

ensure_path("TEXINPUTS", "~/.config/latexmk//");
$success_cmd = "cleantex";
